### ISSUE TITLE
java.lang.ClassNotFoundException: osm.pbf.DefaultSource

### ISSUE THREAD

**Issue by Opalo** [simplexspatial/osm4scala#45]
Hi!

I'm running spark v2.4.6. I've started it with the following command:
```
spark-shell --packages com.acervera.osm4scala:osm4scala-core_2.11:1.0.3
```
and while trying to load the data:
```
val osmDF = spark.sqlContext.read.format("osm.pbf").load("<osm files path here>")
```
I'm getting the following error:
```
java.lang.ClassNotFoundException: Failed to find data source: osm.pbf. Please find packages at http://spark.apache.org/third-party-projects.html
  at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:657)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:194)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:178)
  ... 49 elided
Caused by: java.lang.ClassNotFoundException: osm.pbf.DefaultSource
  at scala.reflect.internal.util.AbstractFileClassLoader.findClass(AbstractFileClassLoader.scala:62)
  at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:953)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:898)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:881)
  at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$20$$anonfun$apply$12.apply(DataSource.scala:634)
  at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$20$$anonfun$apply$12.apply(DataSource.scala:634)
  at scala.util.Try$.apply(Try.scala:192)
  at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$20.apply(DataSource.scala:634)
  at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$20.apply(DataSource.scala:634)
  at scala.util.Try.orElse(Try.scala:84)
  at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:634)
  ... 51 more

```
Is there any other dependency I should add?

**Comment by angelcervera** [comment]
Only Spark 3 is supported. There is a matrix in the readme with which
version to use depending of the Scala version and the Spark version.
Basically   at the moment,  only spark 3 is supported.

If you can not move to spark 3, please, create an issue so I will work on
it.

**Comment by angelcervera** [comment]
Btw, you ate importing the core library. You need to import the spark
controller. There are examples en the readme as well.

**Comment by angelcervera** [comment]
Btw, you are importing the core library. You need to import the spark controller. There are examples en the readme as well.

> bin/spark-shell --packages 'com.acervera.osm4scala:osm4scala-spark-shaded_2.12:1.0.5'

**Comment by Opalo** [comment]
@angelcervera thanks for the prompt response. I'll probably stay with 2.4.6 because of the time pressure. I've also converted my pbf files to parquet and for now happy with that. I don't think if it makes sense to add spark 2.* support, it's up to you :+1:

**Comment by angelcervera** [comment]
@Opalo I'm going to close this issue and create another one to add Spark 2.4.* compatibility, ok? New ticker at #48
